apiVersion: v1
kind: Pod
metadata:
  name: mount-host-etc
  namespace: metarget
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args:
    - |
      echo "K8S_LOG_PROBE_BEGIN"
      id
      ls /host-etc | head || true
      cat /host-etc/hostname || true
      echo "K8S_LOG_PROBE_OK"
      while true; do sleep 30; done
    volumeMounts:
    - name: host-etc
      mountPath: /host-etc
  volumes:
    - name: host-etc
      hostPath:
        path: /etc
