apiVersion: v1
kind: Pod
metadata:
  name: cap-dac-read-search-container
  namespace: metarget
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities:
        add: ["DAC_READ_SEARCH"]
    command: [ "/bin/bash", "-c", "--" ]
    args:
    - |
      echo "K8S_LOG_PROBE_BEGIN"
      id
      grep CapEff /proc/1/status || true
      echo "K8S_LOG_PROBE_OK"
      while true; do sleep 30; done
