apiVersion: v1
kind: Pod
metadata:
  name: mount-docker-sock
  namespace: metarget
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args:
    - |
      echo "K8S_LOG_PROBE_BEGIN"
      id
      ls -l /var/run/docker.sock || true
      echo "K8S_LOG_PROBE_OK"
      while true; do sleep 30; done
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
