apiVersion: v1
kind: Pod
metadata:
  name: mount-host-procfs
  namespace: metarget
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args:
    - |
      echo "K8S_LOG_PROBE_BEGIN"
      id
      cat /host-proc/sys/kernel/core_pattern || true
      ls /host-proc | head || true
      echo "K8S_LOG_PROBE_OK"
      while true; do sleep 30; done
    volumeMounts:
    - name: host-procfs
      mountPath: /host-proc
  volumes:
    - name: host-procfs
      hostPath:
        path: /proc
